In [1]:
import numpy as np
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)
print(ys)
z=np.sqrt(xs**2+ys**2)
print(z)

[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]
[[7.07106781 7.06400028 7.05693985 ... 7.04988652 7.05693985 7.06400028]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 ...
 [7.04988652 7.04279774 7.03571603 ... 7.0286414  7.03571603 7.04279774]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]]


In [5]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=np.where(cond,xarr,yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [9]:
arr=np.random.randn(4,4)
print(arr)
print(arr>0)
print(np.where(arr>0,2,-2))
print(np.where(arr>0,2,arr))

[[-0.31433855 -0.47987191  1.82289685 -0.54808922]
 [ 1.14885669  0.48364615 -0.84037318  0.18054803]
 [ 1.08966459 -0.94788039 -0.95788677 -0.10350206]
 [ 1.18369383  2.03460342 -1.50164302  0.90806416]]
[[False False  True False]
 [ True  True False  True]
 [ True False False False]
 [ True  True False  True]]
[[-2 -2  2 -2]
 [ 2  2 -2  2]
 [ 2 -2 -2 -2]
 [ 2  2 -2  2]]
[[-0.31433855 -0.47987191  2.         -0.54808922]
 [ 2.          2.         -0.84037318  2.        ]
 [ 2.         -0.94788039 -0.95788677 -0.10350206]
 [ 2.          2.         -1.50164302  2.        ]]


In [11]:
arr=np.random.randn(5,4)
print(arr)
print(arr.mean())
print(arr.sum())
print(arr.mean(axis=1))
print(arr.mean(axis=0))

[[-1.32085803 -1.05847759 -1.48708893 -1.01005734]
 [-0.25098062 -0.39382441 -0.98301924 -1.12930576]
 [-0.54971767 -0.65225954 -0.18737561  0.46779874]
 [ 1.00005206 -0.47192255 -1.42652026 -0.38850917]
 [ 0.68960083 -0.29058736  0.3676305  -0.26103483]]
-0.4668228388160009
-9.336456776320018
[-1.21912047 -0.68928251 -0.23038852 -0.32172498  0.12640229]
[-0.08638069 -0.57341429 -0.74327471 -0.46422167]


In [19]:
arr=np.array([0,1,2,3,4,5,6,7])
print(arr.cumsum())

[ 0  1  3  6 10 15 21 28]


In [21]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)
print(arr.cumsum(axis=0))
print(arr.cumprod(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [3]:
import numpy as np
bools=np.array([False,False,True,False])
print(bools.any())
print(bools.all())

True
False


In [13]:
arr=np.random.randn(5)
print(arr)
arr.sort()
print(arr)


[ 0.66705069 -1.13102112 -0.47894592 -0.29914767  0.72438587]
[-1.13102112 -0.47894592 -0.29914767  0.66705069  0.72438587]


In [15]:
arr=np.random.randn(5,3)
print(arr)
arr.sort(1)
print(arr)
arr.sort(0)
print(arr)

[[-0.59207618 -1.79475306 -0.27043185]
 [ 0.57848851 -0.382154   -0.72846499]
 [-1.33728094 -1.21836079  0.48267249]
 [-0.0726027   0.81668949  1.02589258]
 [-0.81506277  0.77515337 -0.6167053 ]]
[[-1.79475306 -0.59207618 -0.27043185]
 [-0.72846499 -0.382154    0.57848851]
 [-1.33728094 -1.21836079  0.48267249]
 [-0.0726027   0.81668949  1.02589258]
 [-0.81506277 -0.6167053   0.77515337]]
[[-1.79475306 -1.21836079 -0.27043185]
 [-1.33728094 -0.6167053   0.48267249]
 [-0.81506277 -0.59207618  0.57848851]
 [-0.72846499 -0.382154    0.77515337]
 [-0.0726027   0.81668949  1.02589258]]


In [17]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
np.unique(names)


array(['bob', 'joe', 'will'], dtype='<U4')

In [19]:
ints=np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [21]:
sorted(set(names))

['bob', 'joe', 'will']

In [37]:
values=np.array([6,0,0,3,2,5,6])
print(np.in1d(values,[2,3,6]))



[ True False False  True  True False  True]


In [56]:
arr=np.arange(10)
np.save('some_array',arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
brr=np.arange(10)
np.save('some_array',brr)
print(brr)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
np.load('some_array.npy'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.savez('array_arch.npz',a=arr,b=brr)
np.load('array_arch.npz')
print(arch['b'])

NameError: name 'arch' is not defined

In [66]:
np.savez_compressed('array_com.npz',a=arr,b=brr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
